/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WeeklyUpdatesRouteImport } from './routes/weekly-updates'
import { Route as RecordIdRouteImport } from './routes/record.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyUpdatesRoute = WeeklyUpdatesRouteImport.update({
  id: '/weekly-updates',
  path: '/weekly-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIdRoute = RecordIdRouteImport.update({
  id: '/record/$id',
  path: '/record/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ideas': typeof IdeasRoute
  '/my-work': typeof MyWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/weekly-updates': typeof WeeklyUpdatesRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ideas': typeof IdeasRoute
  '/my-work': typeof MyWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/weekly-updates': typeof WeeklyUpdatesRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ideas': typeof IdeasRoute
  '/my-work': typeof MyWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/weekly-updates': typeof WeeklyUpdatesRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/ideas'
    | '/my-work'
    | '/portfolio'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/weekly-updates'
    | '/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/ideas'
    | '/my-work'
    | '/portfolio'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/weekly-updates'
    | '/record/$id'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/ideas'
    | '/my-work'
    | '/portfolio'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/weekly-updates'
    | '/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  IdeasRoute: typeof IdeasRoute
  MyWorkRoute: typeof MyWorkRoute
  PortfolioRoute: typeof PortfolioRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WeeklyUpdatesRoute: typeof WeeklyUpdatesRoute
  RecordIdRoute: typeof RecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-updates': {
      id: '/weekly-updates'
      path: '/weekly-updates'
      fullPath: '/weekly-updates'
      preLoaderRoute: typeof WeeklyUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$id': {
      id: '/record/$id'
      path: '/record/$id'
      fullPath: '/record/$id'
      preLoaderRoute: typeof RecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  IdeasRoute: IdeasRoute,
  MyWorkRoute: MyWorkRoute,
  PortfolioRoute: PortfolioRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WeeklyUpdatesRoute: WeeklyUpdatesRoute,
  RecordIdRoute: RecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
